# Generated by Django 5.2.6 on 2026-02-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('description', models.TextField()),
                ('recommended_action', models.TextField()),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tool_signature', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
